version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/:ro
      - ./data/certbot/conf:/etc/letsencrypt/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt/:rw
      - ./data/certbot/www:/var/www/certbot/:rw
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - '8080'
    ports:
      - '8080:3000'
    command: npm run dev
